bundler_args: --without development
language: ruby
rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - jruby-19mode
  - jruby-19mode
  - jruby-head
  - rbx-2
  - ruby-head
matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: jruby-19mode
    - rvm: rbx-2
    - rvm: ruby-head
  fash_finish: true
sudo: false
